sudo: required
services:
    - docker

before_install:
    - docker build -t holyhoppsan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true holyhoppsan/react-test npm test

after_success:
    - docker build -t holyhoppsan/multi-client ./client
    - docker build -t holyhoppsan/multi-nginx ./nginx
    - docker build -t holyhoppsan/multi-server ./server
    - docker build -t holyhoppsan/multi-worker ./worker

    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push holyhoppsan/multi-client 
    - docker push holyhoppsan/multi-nginx
    - docker push holyhoppsan/multi-server
    - docker push holyhoppsan/multi-worker